# example workflow configuration
recipient_key: recipient_key
source:
  type: "S3"
  root_path: "my-bucket/prefix/"
  connection:  # all elements will be passed to the selected snakemake remote provider
    access_key_id: "MYACCESSKEY"
    secret_access_key: "MYSECRET"
    host: http://localhost:9000
    verify: false # don't verify ssl certificates

destination:
  type: "S3"
  root_path: "my-bucket/prefix/"
  connection:  # all elements will be passed to the selected snakemake remote provider
    access_key_id: "MYACCESSKEY"
    secret_access_key: "MYSECRET"
    host: http://localhost:9000
    verify: false # don't verify ssl certificates


filter:
  include:
    - ".tiff.c4gh"
