$schema: "https://json-schema.org/draft/2020-12/schema"
description: Configuration schema for get-data workflow.
properties:
  recipient_key:
    type: string
    description: Path to recipient's c4gh private key.  Must be within working directory tree.
  source:
    type: object
    description: Source of encrypted data
    required:
    - type
    - connection
    properties:
      type:
        type: string
        descrition: Any of the [remote providers supported by snakemake](https://snakemake.readthedocs.io/en/v6.13.1/snakefiles/remote_files.html#remote-files).
        enum:
        - "AzBlob"
        - "dropbox"
        - "EGA"
        - "FTP"
        - "gfal"
        - "gridftp"
        - "GS"
        - "HTTP"
        - "iRODS"
        - "NCBI"
        - "S3"
        - "SFTP"
        - "webdav"
        - "XRootD"
      root_path:
        type: string
        description: Prefix path for source. The workflow will look for files under this path.
        default: "/"
      connection:
        type: object
        description: >
          Connection parameters for [Snakemake remote
          provider](https://snakemake.readthedocs.io/en/v6.13.1/snakefiles/remote_files.html#remote-files).
          Keys required/supported vary depending on the provider type.  See
          the snakemake documentation for details.
        example:
          access_key_id: "MYACCESSKEY"
          secret_access_key: "MYSECRET"
          host: http://localhost:9000
          verify: false

  destination:
    type: object
    description: Destination for decrypted data
    required:
    - type
    properties:
      type:
        type: string
        descrition: >
          Any of the [remote providers supported by snakemake](https://snakemake.readthedocs.io/en/v6.13.1/snakefiles/remote_files.html#remote-files)
        plus "local". Default value: "local"
        default: "local"
        enum:
        - "local"
        - "AzBlob"
        - "dropbox"
        - "EGA"
        - "FTP"
        - "gfal"
        - "gridftp"
        - "GS"
        - "HTTP"
        - "iRODS"
        - "NCBI"
        - "S3"
        - "SFTP"
        - "webdav"
        - "XRootD"
      root_path:
        type: string
        description: Prefix path for destination. Content will be placed under this path.
        default: "/"
      connection:
        type: object
        description: >
          Connection parameters for [Snakemake remote
          provider](https://snakemake.readthedocs.io/en/v6.13.1/snakefiles/remote_files.html#remote-files).
          Keys required/supported vary depending on the provider type.  See
          the snakemake documentation for details.
        example:
          access_key_id: "MYACCESSKEY"
          secret_access_key: "MYSECRET"
          host: http://localhost:9000
          verify: false

  filter:
    type: object
    properties:
      exclude:
        description: >
          Specify a list of glob patterns of files to exclude.  An item is excluded if:
            1. it matches an exclude pattern and does not match any include pattern;
            2. one or more include patterns are specified and none match the item.
        type: array
        items:
          type: string
          description: Glob pattern
      include:
        description: >
          Specify a list of glob patterns of files to include.  If no include pattern
          is specified, all files are included.
        type: array
        items:
          type: string
          description: Glob pattern
  required:
    oneOf:
      - exclude
      - include
required:
- recipient_key
- source
- destination

examples:
  recipient_key: ./recipient_key
  repository:
    path: "/mnt/rbd/data/sftp/fair-crcc/"
    private_key: bbmri-key
    public_key: bbmri-key.pub
  sources:
    glob_extension: ".tiff.c4gh"
    items:
    - some/directory/to/glob
    - another/individual/file.tiff.c4gh
  destination:
    type: "S3"
    root_path: "bucket/subpath/"
    connection:  # all elements will be passed to the selected snakemake remote provider
      access_key_id: "MYACCESSKEY"
      secret_access_key: "MYSECRET"
      host: http://localhost:9000
      verify: false # don't verify ssl certificates
