$schema: "https://json-schema.org/draft/2020-12/schema"
description: Configuration schema for get-data workflow.
properties:
  recipient_key:
    type: string
    description: >
      Path to recipient's c4gh private key.  Must be within working directory tree.
  source:
    type: object
    description: Source of encrypted data.
    required:
    - type
    - connection
    properties:
      type:
        description: >
          Any of the [remote providers supported by snakemake](https://snakemake.readthedocs.io/en/v6.13.1/snakefiles/remote_files.html#remote-files).
        allOf:
        - {$ref: "#/$defs/connection_type"}

      root_path:
        allOf:
          - {$ref: "#/$defs/root_path"}
          - description: >
              Prefix path for source. The workflow will look for files under this path.
      connection:
        {$ref: "#/$defs/connection"}

  destination:
    type: object
    description: >
      Destination for decrypted data.
    required:
    - type
    properties:
      type:
        oneOf: # extend the list of supported connection types with "local"
        - type: string
          enum: [ "local" ]
        - {$ref: "#/$defs/connection_type"}
        default: "local"
        description: >
          Any of the [remote providers supported by snakemake](https://snakemake.readthedocs.io/en/v6.13.1/snakefiles/remote_files.html#remote-files)
          plus "local". Default value: "local"

      root_path:
        allOf:
          - {$ref: "#/$defs/root_path"}
          - description: >
              Prefix path for destination.  The workflow will re-create the original
              source directory structure at the destination storage and under this path.

      connection:
        {$ref: "#/$defs/connection"}

  filters:
    type: array
    items:
      {$ref: "#/$defs/rule"}
    description: >
      Optional list of of filters to be applied to destination file names.
      These are the original names of the files and the names with which they
      will be saved in the specified destination.  The filters follow a logic
      similar to rsync (for those who are familiar with that tool).

      Each filter specifies a glob expression for matching files and an
      "include" or "exclude" action that they apply, if they match a file.  The
      filters are tried in the order they are specified: the first one that
      matches is applied; if no filters match a file name, the file is included.

required:
- recipient_key
- source
- destination

examples:
  recipient_key: ./recipient_key
  repository:
    path: "/mnt/rbd/data/sftp/fair-crcc/"
    private_key: bbmri-key
    public_key: bbmri-key.pub
  sources:
    glob_extension: ".tiff.c4gh"
    items:
    - some/directory/to/glob
    - another/individual/file.tiff.c4gh
  destination:
    type: "S3"
    root_path: "bucket/subpath/"
    connection:  # all elements will be passed to the selected snakemake remote provider
      access_key_id: "MYACCESSKEY"
      secret_access_key: "MYSECRET"
      host: http://localhost:9000
      verify: false # don't verify ssl certificates
  filters:
  - action: "exclude"
    pattern: "test-file_2.txt"

$defs:
  rule:
    type: object
    properties:
      pattern:
        type: string
      action:
        type: string
        enum:
        - "include"
        - "exclude"
    required:
    - action
    - pattern

  connection_type:
    type: string
    enum:
    - "AzBlob"
    - "dropbox"
    - "EGA"
    - "FTP"
    - "gfal"
    - "gridftp"
    - "GS"
    - "HTTP"
    - "iRODS"
    - "NCBI"
    - "S3"
    - "SFTP"
    - "webdav"
    - "XRootD"

  connection:
    type: object
    description: >
      Connection parameters for [Snakemake remote
      provider](https://snakemake.readthedocs.io/en/v6.13.1/snakefiles/remote_files.html#remote-files).
      Keys required/supported vary depending on the provider type.  See
      the snakemake documentation for details.
    example:
      access_key_id: "MYACCESSKEY"
      secret_access_key: "MYSECRET"
      host: http://localhost:9000
      verify: false

  root_path:
    type: string
    default: "/"
